### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by hermanbergwerf** [timneutkens/urlencoded-body-parser#1]
I'm not sure what nodejs version/config you use, but for me node fails to run this, and throws a SyntaxError:
```
.../node_modules/urlencoded-body-parser/dist.js:3
const { parse } = require('qs')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (.../web/server.js:12:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Apparently it doesn't like this line: https://github.com/timneutkens/urlencoded-body-parser/blob/1a06ea95311dd589ad4c38ef3f9cf6236e490049/index.js#L3

**Comment by timneutkens** [comment]
node.js 6+. The thing you're looking at is called destructuring. I'll create an update to support node.js 4+ if you want 👍
